a third banner ad is bourned
desert-planet/ayp pull request #64
Opened 2024-05-03 17:57 UTC by ChillyRelleno

2024-05-07 22:56 UTC, sshirokov commented
Please add the banner image to the description.

2024-05-07 22:58 UTC, sshirokov requested changes

2024-05-07 22:58 UTC, sshirokov commented on lib/app.coffee
> +      #ad = if Math.random() > 0.5 then ads[0] else ads[1]
If you're replacing the code, you don't need the comment, you just replace the code.

2024-05-07 22:58 UTC, sshirokov commented on lib/app.coffee
> +	  ad = ads[Math.floor(math.random()*3)]
Why did the indentation change?

2024-05-07 22:58 UTC, sshirokov commented on lib/app.coffee
> +	  ad = ads[Math.floor(math.random()*3)]
Now that there are not two, that constant `3` should instead be the actual length of `ads`

2024-05-07 22:59 UTC, sshirokov commented on lib/app.coffee
> +	  ad = ads[Math.floor(math.random()*3)]
Also, I'm not gonna do the math, but I'm pretty sure `Math.floor()` isn't as good of a distribution as `Math.round`

2024-05-07 23:00 UTC, sshirokov requested changes

2024-05-07 23:00 UTC, sshirokov commented on lib/app.coffee
> +		'<a href="https://www.youtube.com/channel/UCke_95iHaMHXxzD13TpCR4Q" title="Arctic Taco Gaming"><img alt="Ad for Arctic Taco Gaming" src="/static/images/ayp_atg.png"></a>',
Indentation wtf here as well.

2024-05-07 23:03 UTC, ChillyRelleno commented on lib/app.coffee
> +	  ad = ads[Math.floor(math.random()*3)]
Tabs vs spaces.

2024-05-07 23:04 UTC, ChillyRelleno commented on lib/app.coffee
> +		'<a href="https://www.youtube.com/channel/UCke_95iHaMHXxzD13TpCR4Q" title="Arctic Taco Gaming"><img alt="Ad for Arctic Taco Gaming" src="/static/images/ayp_atg.png"></a>',
why is it like this

2024-05-07 23:08 UTC, sshirokov requested changes

2024-05-07 23:08 UTC, sshirokov commented on lib/app.coffee
> +      ad = ads[Math.floor(math.random()*ads.length)]
```suggestion
      ad = ads[Math.floor(Math.random()*ads.length)]
```

`Math` is capitalized

2024-05-07 23:08 UTC, sshirokov commented on lib/app.coffee
> +      ad = ads[Math.floor(math.random()*ads.length)]
And I'm guessing that you don't care if the distribution is even? I'm also not sure nor do I know if it matters.

2024-05-08 02:49 UTC, ChillyRelleno reviewed
looks like decent c to me!

2024-05-08 03:07 UTC, sshirokov approved these changes

2024-05-08 03:08 UTC, merged